/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>
#include "stm32f4xx.h"
#include "stm32f4xx_gpio.h"
#include "stm32f4xx_spi.h"

/*
 * SPI notes
 */
/*
 * PB12:	SPI2_NSS
 * PB13:	SPI2_SCK
 * PB14:	SPI2_MISO
 * PB15:	SPI2_MOSI
 * Alternate function 5
 */


GPIO_Handler_t GPIOLED, GPIOButton;


void delay() {
	for (uint32_t i = 0; i < 500000/2; i++);
}

void GPIO_ExButton(void) {
	GPIOLED.pGPIOx = GPIOA;
	GPIOLED.pPinConfig.GPIO_PinMode = GPIO_MODE_OUTPUT;
	GPIOLED.pPinConfig.GPIO_PinNumber = GPIO_PIN_08;
	GPIOLED.pPinConfig.GPIO_PinOType = GPIO_OTYPE_PUSH_PULL;
	GPIOLED.pPinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
	GPIOLED.pPinConfig.GPIO_PinSpeed = GPIO_SPEED_VERYHIGH;

	GPIO_PeriClockControl(GPIOA, ENABLE);
	GPIO_Init(&GPIOLED);

	GPIOButton.pGPIOx = GPIOD;
	GPIOButton.pPinConfig.GPIO_PinMode = GPIO_MODE_INPUT_FT;
	GPIOButton.pPinConfig.GPIO_PinNumber = GPIO_PIN_05;
	GPIOButton.pPinConfig.GPIO_PinPuPdControl = GPIO_PU;
	GPIOButton.pPinConfig.GPIO_PinOType = GPIO_OTYPE_PUSH_PULL;
	GPIOButton.pPinConfig.GPIO_PinSpeed = GPIO_SPEED_VERYHIGH;

	GPIO_PeriClockControl(GPIOD, ENABLE);
	GPIO_Init(&GPIOButton);
	GPIO_IRQConfig(IRQ_NO_EXTI9_5, 0, ENABLE);
}

void GPIO_ForSPI(void){
	GPIO_Handler_t SPIGPIO;

	SPIGPIO.pGPIOx = GPIOB;
	SPIGPIO.pPinConfig.GPIO_PinAltFunMode = GPIO_AF_05;
	SPIGPIO.pPinConfig.GPIO_PinMode = GPIO_MODE_ALT;
	SPIGPIO.pPinConfig.GPIO_PinOType = GPIO_OTYPE_PUSH_PULL;
	SPIGPIO.pPinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
	SPIGPIO.pPinConfig.GPIO_PinSpeed = GPIO_SPEED_VERYHIGH;

	GPIO_PeriClockControl(GPIOB, ENABLE);
//
//	SPIGPIO.pPinConfig.GPIO_PinNumber = GPIO_PIN_12;
//	GPIO_Init(&SPIGPIO);

	SPIGPIO.pPinConfig.GPIO_PinNumber = GPIO_PIN_13;
	GPIO_Init(&SPIGPIO);

//	SPIGPIO.pPinConfig.GPIO_PinNumber = GPIO_PIN_14;
//	GPIO_Init(&SPIGPIO);

	SPIGPIO.pPinConfig.GPIO_PinNumber = GPIO_PIN_15;
	GPIO_Init(&SPIGPIO);
}

void SPI_Application_Init(void){
	SPI_Handler_t SPI_App;

	SPI_App.pSPIx = SPI2;

	SPI_App.SPIConfig.SPI_BusConfig = SPI_BUSCONFIG_FD;
	SPI_App.SPIConfig.SPI_CPHA = SPI_CPHA_FIRST_CAPTURE;
	SPI_App.SPIConfig.SPI_CPOL = SPI_CPOL_LOW;
	SPI_App.SPIConfig.SPI_DataFormat = SPI_DFF_8_BIT;
	SPI_App.SPIConfig.SPI_DeviceMode = SPI_DEVICE_MODE_MASTER;
	SPI_App.SPIConfig.SPI_SSM = SPI_SSM_SW;
	SPI_App.SPIConfig.SPI_SclkSpeed = SPI_SCLK_DEVIDE_8;

	SPI_PeriClockControl(SPI2, ENABLE);
	SPI_Init(&SPI_App);
}

int main(void)
{
	char* user_data = "Hello From User";
	// Initialize for GPIOs pin related with SPI
	GPIO_ForSPI();
	// Initialize SPI peripheral
	SPI_Application_Init();
	// Assign HIGH to SSI pin
	SPI_EnableNSSPin(SPI2, ENABLE);
	// Enable start SPI
	SPI_EnableSPI(SPI2, ENABLE);
	// Send data
	SPI_SendData(SPI2, (uint8_t*)user_data, strlen(user_data));
	// Disable start SPI
	SPI_EnableSPI(SPI2, DISABLE);

	while(1){
		// Do nothing
	}
}

void EXTI9_5_IRQHandler(void){
	GPIO_IRQHandling(5);
}
