/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

#define RCC_BASEADDRESS						0x40023800UL
#define GPIOC_BASEADDRESS					0x40020800UL

#define RCC_CR								*(uint32_t* )(RCC_BASEADDRESS + 0x00UL)
#define RCC_CFGR							*(uint32_t* )(RCC_BASEADDRESS + 0x08UL)
#define RCC_AHB1							*(uint32_t* )(RCC_BASEADDRESS + 0x30UL)

#define GPIOC_MODER							*(uint32_t* )(GPIOC_BASEADDRESS + 0x00UL)
#define GPIOC_AFRH							*(uint32_t* )(GPIOC_BASEADDRESS + 0x24UL)


int main(void)
{
    /* Loop forever */
	// Enable HSE clock
	RCC_CR |= (0x1<<16);
	while(!(RCC_CR & 0x20000));

	// Set HSE to SystemClock
	RCC_CFGR &= ~(0x3<<0); 	// Clear 2 bits 0:1
	RCC_CFGR |= (0x1);		// set to 01
	while(((RCC_CFGR & 0xC)>>2) != 0x1);

	// Set measurement to MCO2
	RCC_CFGR &= ~(0x3<<30);
	RCC_CFGR |= (0x2 << 30);
	RCC_CFGR |= (1 << 28);
	RCC_CFGR |= (1 << 29);

	// Enable clock GPIOC
	RCC_AHB1 |= (0x1 << 2);

	// Set alternate function mode for PC9
	GPIOC_MODER &= ~(0x3 << 18);
	GPIOC_MODER |= (0x2 << 18);

	// Set AF0 for PC9
	GPIOC_AFRH &= ~(0xf << 4);

	for(;;);
}
